export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_FAILED = 'GET_BOOKINGS_FAILED';
export const REORDER_BOOKINGS_DND = 'REORDER_BOOKINGS_DND';
export const MOVE_BOOKINGS_DND_SUCCESS = 'MOVE_BOOKINGS_DND_SUCCESS';
export const MOVE_BOOKINGS_DND_FAILED = 'MOVE_BOOKINGS_DND_FAILED';
export const CANCEL_BOOKING_FAILED = 'CANCEL_BOOKING_FAILED';
